### ISSUE TITLE
Latest release causes issue with WP Project Manager - Frontend Plugin

### ISSUE THREAD

**Issue by chrisradford** [tareq1988/wp-project-manager#51]
Version 0.4.5 of the WP Project Manager plugin causes an issue with version 1.2.1 of the WP Project Manager - Frontend plugin. Since the update the page title (of the page containing the shortcode) shows as a project alongside the projects from the backend.

**Comment by tareq1988** [comment]
Duplicate #52

**Comment by chrisradford** [comment]
This isn't a duplicate of #52 — that issue is regarding the 'New Project' popup whilst this one is related to the addition of the page title as a project link below the list of projects when using `[cpm]`.

![screen shot 2015-01-26 at 22 03 09](https://cloud.githubusercontent.com/assets/743548/5909309/3a630804-a5a7-11e4-8f78-49310749f77b.png)
