### ISSUE TITLE
Error with creating a project

### ISSUE THREAD

**Issue by M0nkfiish** [tareq1988/wp-project-manager#54]
Hi There, 

I get the following error when trying to add a new project - if I refresh the page the project has been added, but when clicking the settings icon I get the same error:

Warning: array_key_exists() expects parameter 2 to be array, null given in /home/dvelopit/public_html/project/wp-content/plugins/wedevs-project-manager/class/project.php on line 605

*Currently using the free version of the plugin.

Any advice appreciated, thanks.

**Comment by asaquzzaman** [comment]
Sorry I does not find this kind of error in my testing environment. Please provide me your ftp and wp-admin access. I will fix your problem.

**Comment by M0nkfiish** [comment]
seems to be working since updating to latest version. Thanks
