### ISSUE TITLE
Created users cant be saved 

### ISSUE THREAD

**Issue by ELyukio** [tareq1988/wp-project-manager#55]
In the pro manager 1.3.4 the users cant be saved in the project, the users log is there butwhen you save the new project alll the users disapear

**Comment by rjrobertsjr** [comment]
I'm having the same issue. Even when my users were already created, they cannot be "added" to the project and do not show up in the list of notifications.
![image](https://cloud.githubusercontent.com/assets/14876702/10142797/583631aa-65da-11e5-9948-ca97d799b9e8.png) This image should show 4 users, but none of them show up.

**Comment by rjrobertsjr** [comment]
I see that the update is available for WP Project Manager, but when will the update be available for WP Project Manager Pro?

**Comment by tareq1988** [comment]
The PRO version was updated at the same time.

**Comment by ELyukio** [comment]
HELLO

Tareq, thanks!

 but another issue comes up,

the woo project doesn't work.



2015-09-29 14:42 GMT-05:00 Tareq Hasan <notifications@github.com>:
